//  AUTOMATIC SEMICOLON GENERATION PART 2.


var a = 12 // <-- LIKE IN PART 1, THE AUTO SEMICOLON ADDITION APPLIES HERE AND FOR var b.

var b = 13

var c = b + a // <-- THINGS GET WEIRD HERE. THE NEXT CHARACTER FROM LEFT TO RIGHT TO THE COMPILER IS THIS []. THIS IS ALLOWED BECAUSE THE COMPILER IS THINKING THAT
              // YOU ARE BRACKETING INTO AN ARRAY SO IT WILL NOT PUT A SEMICOLON THERE. THIS CODE WILL THROW AN ERROR BECAUSE THERES A SUB BRACKET THAT ISN'T DEFINED. 
              // ( ['menu', 'items', 'listed'] ). YOU CANT DO THIS a[1,2,3].forEach(). SO YOU NEED TO MANUALLY ADD A SEMICOLON AT THE END OF a ON THE VARIABLE c.

['menu', 'items', 'listed']
    .forEach(function(element) {
        console.log(element)
    })

// RUN THE CODE AS IS TO SEE THE ERROR THEN ADD A SEMICOLON TO THE END OF var c = b + a(;).